name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: graph-ql-app

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setting up JVM
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build Jar
        run: mvn run package -DskipTests